"""
main.py — Orchestrator and entry point for Smart Packet Inspector.
Provides a real-time terminal dashboard displaying network traffic analysis.
"""

import argparse
import sys
import time
import signal
import threading
from pathlib import Path

from rich.console import Console
from rich.live import Live
from rich.layout import Layout
from rich.panel import Panel
from rich.table import Table
from rich.text import Text
from rich import box

from sniffer import PacketSniffer
from analyzer import TrafficAnalyzer
from logger import PacketLogger

console = Console()

# ── shared state ──────────────────────────────────────────────────────────────
_packet_feed: list[dict] = []  # Rolling display buffer for live feed
_FEED_MAX = 30
_lock = threading.Lock()
_analyzer = TrafficAnalyzer()
_logger: PacketLogger | None = None
_running = True
_logged_alerts_count = 0


# ── utilities ─────────────────────────────────────────────────────────────────

def format_bytes(n_bytes: int) -> str:
    """Format bytes to human-readable size."""
    for unit in ['B', 'KB', 'MB', 'GB']:
        if n_bytes < 1024.0:
            return f"{n_bytes:.1f} {unit}" if unit != 'B' else f"{n_bytes} B"
        n_bytes /= 1024.0
    return f"{n_bytes:.1f} TB"


# ── callbacks ─────────────────────────────────────────────────────────────────

def on_packet_captured(packet_data: dict):
    """Callback for PacketSniffer when a new packet is captured."""
    global _logged_alerts_count
    
    # Ingest packet into analyzer
    _analyzer.ingest(packet_data)

    # Log packet to disk if logger is enabled
    if _logger:
        try:
            _logger.log(packet_data)
        except Exception:
            pass

    # Check for new alerts generated by analyzer and log them
    alerts = _analyzer.get_alerts()
    if len(alerts) > _logged_alerts_count:
        new_alerts = alerts[_logged_alerts_count:]
        for alert in new_alerts:
            if _logger:
                try:
                    _logger.log_alert(alert)
                except Exception:
                    pass
        _logged_alerts_count = len(alerts)

    # Append to rolling live feed under lock
    with _lock:
        _packet_feed.append(packet_data)
        if len(_packet_feed) > _FEED_MAX:
            _packet_feed.pop(0)


# ── UI builders ───────────────────────────────────────────────────────────────

def build_packet_feed_table(feed: list) -> Table:
    """Build the live packet feed table."""
    t = Table(
        title="📡 Live Packet Feed",
        box=box.SIMPLE_HEAD,
        expand=True,
        border_style="cyan",
        show_lines=False,
    )
    t.add_column("Timestamp", style="dim", width=12)
    t.add_column("Proto", justify="center", width=8)
    t.add_column("Source IP", justify="left", width=16)
    t.add_column("Destination IP", justify="left", width=16)
    t.add_column("Ports", justify="center", width=14)
    t.add_column("Size", justify="right", width=8)

    for pkt in reversed(feed[-25:]):
        proto = pkt.get("protocol", "OTHER")
        if proto == "TCP":
            proto_styled = "[bold blue]TCP[/bold blue]"
        elif proto == "UDP":
            proto_styled = "[bold green]UDP[/bold green]"
        elif proto == "ICMP":
            proto_styled = "[bold red]ICMP[/bold red]"
        elif proto == "HTTP":
            proto_styled = "[bold yellow]HTTP[/bold yellow]"
        else:
            proto_styled = f"[dim]{proto}[/dim]"

        src_port = pkt.get("src_port")
        dst_port = pkt.get("dst_port")
        ports_str = f"{src_port}→{dst_port}" if src_port is not None and dst_port is not None else "-"
        
        ts = pkt.get("timestamp", "")
        if " " in ts:
            ts = ts.split(" ")[1]  # Keep only time part (HH:MM:SS.mmm)

        t.add_row(
            ts,
            proto_styled,
            pkt.get("src_ip", "-"),
            pkt.get("dst_ip", "-"),
            ports_str,
            f"{pkt.get('size', 0)} B",
        )
    return t


def build_stats_panel(stats: dict, active_filters: dict) -> Panel:
    """Build the traffic statistics panel."""
    total_pkts = stats.get("total_packets", 0)
    total_bytes_val = stats.get("total_bytes", 0)
    pps = stats.get("packets_per_second", 0)
    duration = stats.get("session_duration_sec", 0)
    alerts_cnt = stats.get("alert_count", 0)

    # Active filters representation
    filters_list = []
    if active_filters.get("protocol"):
        filters_list.append(f"Proto:{active_filters['protocol']}")
    if active_filters.get("ip"):
        filters_list.append(f"IP:{active_filters['ip']}")
    if active_filters.get("interface"):
        filters_list.append(f"IFace:{active_filters['interface']}")
    filters_str = ", ".join(filters_list) if filters_list else "None"

    # Protocol counts breakdown
    proto_breakdown = ""
    for proto, count in sorted(stats.get("protocol_counts", {}).items(), key=lambda x: x[1], reverse=True):
        proto_breakdown += f"  [cyan]{proto:<8}[/cyan] : [bright_white]{count:>5,}[/bright_white]\n"
    if not proto_breakdown:
        proto_breakdown = "  [dim](No protocols detected yet)[/dim]\n"

    # Top Source IPs bar graph
    top_ips_str = ""
    top_ips = stats.get("top_source_ips", [])
    max_count = max([cnt for ip, cnt in top_ips]) if top_ips else 1
    for ip, count in top_ips:
        bar_len = min(int((count / max_count) * 10), 10) if max_count > 0 else 0
        bar = "█" * bar_len
        top_ips_str += f"  {ip:<15} [green]{bar:<10}[/green] {count:>4}\n"
    if not top_ips_str:
        top_ips_str = "  [dim](No traffic sources yet)[/dim]\n"

    body = (
        f"[bold]Total Packets    :[/bold]  [bright_white]{total_pkts:>8,}[/bright_white]\n"
        f"[bold]Total Bytes      :[/bold]  [bright_white]{format_bytes(total_bytes_val):>8}[/bright_white]\n"
        f"[bold]Packets / Sec    :[/bold]  [cyan]{pps:>8.2f}[/cyan]\n"
        f"[bold]Session Time     :[/bold]  [bright_white]{duration:>7.1f}s[/bright_white]\n"
        f"[bold]Active Filters   :[/bold]  [yellow]{filters_str}[/yellow]\n"
        f"[bold]Anomaly Alerts   :[/bold]  [red]{alerts_cnt:>8}[/red]\n"
        f"\n[bold underline]Protocol Breakdown[/bold underline]\n{proto_breakdown}"
        f"\n[bold underline]Top Traffic Sources[/bold underline]\n{top_ips_str}"
    )
    return Panel(body, title="📊 Traffic Statistics", border_style="green", padding=(0, 1))


def build_alerts_panel(alerts: list) -> Panel:
    """Build the anomaly alerts panel."""
    if not alerts:
        body = "[dim]No anomalies or floods detected.[/dim]"
    else:
        rows = []
        for a in reversed(alerts[-8:]):
            severity = a.get("severity", "INFO")
            color = "red" if severity == "HIGH" else "yellow"
            ts = a.get("timestamp", "")
            if " " in ts:
                ts = ts.split(" ")[1]
            rows.append(
                f"[bold {color}]⚠ {severity}[/bold {color}] [{color}]{ts}[/{color}] {a.get('message', '')}"
            )
        body = "\n".join(rows)
    return Panel(body, title="🚨 Anomaly Alerts", border_style="red", padding=(0, 1))


def build_header() -> Panel:
    """Build header panel."""
    return Panel(
        Text.from_markup(
            "  [bold cyan]🔬 SMART PACKET INSPECTOR[/bold cyan]  "
            "[dim]| Educational Network Sniffer — Real-Time Traffic Analysis[/dim]"
        ),
        border_style="cyan",
        padding=(0, 1),
    )


def build_footer(log_path: str) -> Text:
    """Build footer text."""
    return Text.from_markup(
        f" [bold green]● ACTIVE CAPTURE[/bold green]    "
        f"[dim]Press Ctrl+C to stop   |   Log → {log_path}[/dim]"
    )


# ── main ──────────────────────────────────────────────────────────────────────

def parse_args():
    """Parse command line arguments."""
    p = argparse.ArgumentParser(
        description="Smart Packet Inspector — Real-Time Network Sniffer",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
EXAMPLES
  python main.py
  python main.py --protocol TCP
  python main.py --ip 192.168.1.100
  python main.py --interface eth0
  python main.py --no-log
  python main.py --session lab_test_01
        """,
    )
    p.add_argument("--protocol", metavar="PROTO",
                   help="Filter by protocol (TCP, UDP, ICMP, HTTP)")
    p.add_argument("--ip", metavar="IP",
                   help="Filter by IP address (source or destination)")
    p.add_argument("--interface", metavar="NIC",
                   help="Specify network interface to sniff on")
    p.add_argument("--no-log", action="store_true",
                   help="Disable logging to disk")
    p.add_argument("--session", metavar="NAME",
                   help="Custom session name prefix for log files")
    return p.parse_args()


def main():
    global _logger, _running

    # Force UTF-8 encoding for standard output and error to prevent encoding issues on Windows
    if sys.stdout.encoding != 'utf-8':
        try:
            sys.stdout.reconfigure(encoding='utf-8')
        except Exception:
            pass
    if sys.stderr.encoding != 'utf-8':
        try:
            sys.stderr.reconfigure(encoding='utf-8')
        except Exception:
            pass

    args = parse_args()
    
    # Render static banner and info notice
    banner_text = """
[bold cyan]╭──────────────────────────────────────────────────────────────────────╮[/bold cyan]
[bold cyan]│  🔬 SMART PACKET INSPECTOR                                           │[/bold cyan]
[bold cyan]│ Network Sniffer — Real-Time Traffic Analysis            │[/bold cyan]
[bold cyan]╰──────────────────────────────────────────────────────────────────────╯[/bold cyan]
    """
    console.print(banner_text)
    console.print("[bold yellow]⚠️  ETHICAL USE NOTICE & DISCLAIMER:[/bold yellow]")
    console.print("This tool is for educational use only in a controlled local environment.")
    console.print("Sniffing network traffic requires administrative/root privileges.")
    console.print("Always ensure you have full authorization before monitoring any network.")
    console.print("Press [bold red]Ctrl+C[/bold red] to stop the capture gracefully.\n")

    # ── setup session log ────────────────────────────────────────────────
    log_path_str = "(disabled)"
    if not args.no_log:
        try:
            _logger = PacketLogger(session_name=args.session)
            _logger.open()
            log_path_str = str(_logger.csv_path.parent / _logger.session_name) + ".*"
            console.print(f"[green]✔[/green] Session log initialized: [cyan]{_logger.csv_path}[/cyan] & [cyan]{_logger.txt_path}[/cyan]")
        except Exception as e:
            console.print(f"[red]❌ Failed to initialize logger: {e}[/red]")
            sys.exit(1)

    # ── start packet sniffer ─────────────────────────────────────────────
    active_filters = {
        "protocol": args.protocol,
        "ip": args.ip,
        "interface": args.interface
    }
    
    sniffer = PacketSniffer(
        packet_callback=on_packet_captured,
        protocol_filter=args.protocol,
        ip_filter=args.ip,
        interface=args.interface
    )
    
    try:
        sniffer.start()
        console.print("[green]✔[/green] Packet capture engine started active background thread.")
        time.sleep(1)  # Brief pause to verify thread starting successfully
        if not sniffer._thread.is_alive():
            raise RuntimeError("Sniffer background thread terminated unexpectedly.")
    except PermissionError:
        console.print("[red]❌ Permission Error: You must run this script with Administrator/Root privileges.[/red]")
        if _logger:
            _logger.close()
        sys.exit(1)
    except Exception as e:
        console.print(f"[red]❌ Failed to start sniffer: {e}[/red]")
        console.print("[yellow]Ensure Npcap is installed (on Windows) or run as Administrator.[/yellow]")
        if _logger:
            _logger.close()
        sys.exit(1)

    # ── signal handler for SIGINT ─────────────────────────────────────────
    def stop_handler(sig, frame):
        global _running
        _running = False

    signal.signal(signal.SIGINT, stop_handler)

    # ── live dashboard loop ───────────────────────────────────────────────
    try:
        with Live(console=console, refresh_per_second=5, screen=True) as live:
            while _running:
                with _lock:
                    feed_snapshot = list(_packet_feed)
                
                stats = _analyzer.get_stats()
                alerts = _analyzer.get_alerts()

                layout = Layout()
                layout.split_column(
                    Layout(build_header(), size=3),
                    Layout(name="body"),
                    Layout(build_footer(log_path_str), size=1),
                )
                layout["body"].split_row(
                    Layout(build_packet_feed_table(feed_snapshot), ratio=3),
                    Layout(name="sidebar", ratio=2),
                )
                layout["body"]["sidebar"].split_column(
                    Layout(build_stats_panel(stats, active_filters), ratio=3),
                    Layout(build_alerts_panel(alerts), ratio=2),
                )
                live.update(layout)
                time.sleep(0.2)

    except KeyboardInterrupt:
        pass
    except Exception as e:
        # Clear screen so error traceback is visible
        console.print(f"\n[red]Dashboard runtime error: {e}[/red]")
    finally:
        # Graceful shutdown of sniffer and logger
        sniffer.stop()
        stats = _analyzer.get_stats()
        alerts = _analyzer.get_alerts()

        if _logger:
            try:
                _logger.write_summary(stats, alerts)
                _logger.close()
            except Exception:
                pass

        console.print()
        console.print(Panel(
            f"[bold]Session Complete[/bold]\n\n"
            f"  Total Packets    : [cyan]{stats['total_packets']:,}[/cyan]\n"
            f"  Total Bytes      : [cyan]{format_bytes(stats['total_bytes'])}[/cyan]\n"
            f"  Session Duration : [cyan]{stats['session_duration_sec']}s[/cyan]\n"
            f"  Average Rate     : [cyan]{stats['packets_per_second']} pps[/cyan]\n"
            f"  Anomaly Alerts   : [red]{stats['alert_count']}[/red]\n"
            + (f"\n  Logs saved to:\n   - [green]{_logger.csv_path}[/green]\n   - [green]{_logger.txt_path}[/green]" if _logger else ""),
            title="[bold green]✔ Capture Session Summary[/bold green]",
            border_style="green",
        ))


if __name__ == "__main__":
    main()
